project:
  type: book
  output-dir: docs

book:
  title: "AB322 Land-2-Sea Tutorial"
  author: "Isabell Eischeid & Maeve McGovern"
  date: "Summer, 2022"
  cover-image: cover.png
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - river_chemistry.qmd
    - spatial_analysis.qmd
    - catchment_comparison.qmd
    - references.qmd
  appendices:
    - additional_work.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: cover.png
    code-link: true





