## Welcome {.unnumbered}

UNIS course AB-322 is titled "Fluxes of Nutrients, Energy and Contaminants from Sea to Land", a title that largely ignores the arguably larger fluxes moving in the opposite direction: from land to sea. 

Here, we have compiled an R tutorial focused on 5 Arctic rivers and their role in transporting nutrients, carbon and contaminants from thawing catchments to coastal waters in Isfjorden, Svalbard. 

### Installing R

This tutorial requires you to have R and Rstudio installed on your computer. Go to the R website and follow the links for downloading. 

R for Windows: https://cran.r-project.org/bin/windows/base/. 

R for Macs: https://cran.r-project.org/bin/macosx/. 

R-studio: https://www.rstudio.com/products/rstudio/download/ 

Once you have Rstudio installed, click on File/New File/Rscript. We will use this new Rscript file for loading, cleaning and plotting catchment and river water chemistry data throughout this tutorial. 

### Install Packages
In addition, you will need to install several R packages. You can do this by copying and running the following lines of code in your new Rscript. 

``` r
# | eval: false
 
# Packages for data preparation and plotting
install.packages(“tidyverse”)
install.packages(“lubridate”)
install.packages(“vegan”)

# Packages for spatial data analysis
install.packages(“sf”)
install.packages(“terra”)
install.packages(“units”)
install.packages(“raster”)
install.packages(“rgeos”)
install.packages(“tmap”)	
```

